module.exports = $importAll([
    "./Array",
    "./Char",
    "./Dict",
    "use:./Errors.estree core:Tool.ESTree:1.0.3",
    "core:Native.System.IO.FileSystem:1.1.0",
    "./Float",
    "core:Native.Data.Int:1.0.0",
    "core:Text.Parsing.Lexer:1.0.0",
    "core:Native.Data.Maybe:1.0.0",
    "core:Text.Parsing.Combinators:1.2.0",
    "core:Native.Data.Result:1.0.0",
    "./Set",
    "use:./SLAST.estree core:Tool.ESTree:1.0.3",
    "core:Data.Collection.InfiniteStream:1.0.0",
    "core:Native.Data.String:1.0.0"
]).then($imports => ({
    Array: $imports[0],
    Char: $imports[1],
    Dict: $imports[2],
    Errors: $imports[3],
    FileSystem: $imports[4],
    Float: $imports[5],
    Int: $imports[6],
    Lexer: $imports[7],
    Maybe: $imports[8],
    ParserCombinator: $imports[9],
    Result: $imports[10],
    Set: $imports[11],
    SLAST: $imports[12],
    Stream: $imports[13],
    String: $imports[14]
}));